import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card";
import { UploadStatus } from "./fileUploader";
import { motion } from "framer-motion";

const Summary = ({ summary }: { summary: string | null }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="w-full max-w-2xl mt-6"
    >
      <Card className="relative bg-gradient-to-br from-rose-50 to-pink-50/20 backdrop-blur-sm border-pink-200/50 shadow-lg hover:shadow-xl transition-shadow">
        {/* Animated border effect */}
        <div className="absolute inset-0 bg-gradient-to-r from-pink-500/10 to-rose-500/10 animate-gradient-rotate rounded-lg" />

        <CardHeader className="text-center">
          <motion.div
            initial={{ scale: 0.9 }}
            animate={{ scale: 1 }}
            className="text-2xl font-bold bg-gradient-to-r from-rose-600 to-orange-500 bg-clip-text text-transparent"
          >
            {summary
              ? "🍅 Here's Your Fresh Ketchup!"
              : "👩🍳 Preparing Your Ketchup..."}
          </motion.div>
        </CardHeader>

        {summary ? (
          <>
            <CardContent className="px-8 pb-6">
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="prose prose-pink font-serif text-gray-700 text-lg leading-relaxed"
              >
                {summary.split("\n").map((line, i) => (
                  <p key={i} className="mb-4">
                    {line}
                  </p>
                ))}
              </motion.div>
            </CardContent>
            <CardFooter className="flex justify-center pb-6">
              <div className="text-sm text-rose-600/70 flex items-center gap-2">
                <span className="animate-pulse">✨</span>
                Generated by BilahiGPT
                <span className="inline-block animate-bounce">🍅</span>
              </div>
            </CardFooter>
          </>
        ) : (
          <motion.div
            className="flex justify-center items-center h-32"
            animate={{
              scale: [1, 1.1, 1],
              rotate: [0, 5, -5, 0],
            }}
            transition={{ repeat: Infinity, duration: 2 }}
          >
            <div className="relative">
              <span className="text-4xl animate-bounce">🍅</span>
              <div className="absolute -top-4 -right-6 text-xl animate-pulse">
                🔥
              </div>
              <div className="absolute -bottom-4 -left-6 text-xl animate-pulse">
                🧂
              </div>
            </div>
          </motion.div>
        )}
      </Card>

      {/* Floating sauce elements */}
      {!summary && (
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/4 left-1/4 text-2xl opacity-20 animate-float">
            🍅
          </div>
          <div className="absolute top-1/3 right-1/4 text-xl opacity-20 animate-float-delayed">
            🥫
          </div>
          <div className="absolute bottom-1/4 left-1/3 text-lg opacity-20 animate-float">
            🌶️
          </div>
        </div>
      )}
    </motion.div>
  );
};

export default Summary;
